name: jest-and-docker-ci

on:
  push:
    branches:
      - main

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: "Install  deps"
        run: cd client && npm i
      - name: Goto client and run tests
        run: cd client && npm run test

  build:
    needs: test-front
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/WildCodeSchool/2209-wns-adleman-mapado:latest
          build-args: |
            "REACT_APP_GRAPHQL_API_URL=${{ vars.REACT_APP_GRAPHQL_API_URL }}"